name: Android CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  update-leveldb:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update leveldb-mcpe
        run: |
          git submodule init
          git submodule update --remote --merge
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git diff --exit-code || git commit -am "CI: Update leveldb-mcpe"
          git push

  build-debug:
    needs: update-leveldb
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Build Debug .apk
      run: |
        ./gradlew :app:assembleDebug
        mkdir -p out
        mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: out/app-debug.apk

  build-release:
    needs: update-leveldb
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build Release .apk
      run: |
        ./gradlew :app:assembleRelease
        mkdir -p out
        mv app/build/outputs/apk/release/app-release.apk out/app-release.apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-release
          path: out/app-release.apk